---
repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: ['flake8-quotes', 'flake8-print']

  - repo: https://github.com/python/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
        args: ['--application-directories', 'app']

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: [--strict, -c=.yamllint.yml, app/config/local.yaml.tmpl]
