---
services:
  nginx:
      build:
        dockerfile: ./deploy/docker/nginx.Dockerfile
        context: .
      ports:
        - "80:80"
      container_name: nginx_course_api
      depends_on:
        - api
  redis:
    image: redis:7
    container_name: redis_course_api
    ports:
      - "${REDIS_PORT:-6501}:6379"
  checker:
    build:
      dockerfile: ./deploy/docker/checker.Dockerfile
      context: .
    container_name: checker
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      POETRY_VIRTUALENVS_CREATE: false
      PYTHONPATH: "/project/app"
    depends_on:
      - redis
  api:
    build:
      dockerfile: ./deploy/docker/api.Dockerfile
      context: .
    container_name: course_api
    expose:
      - 7070
    ports:
      - "${API_PORT:-7070}:7070"
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      POETRY_VIRTUALENVS_CREATE: false
      PYTHONPATH: "/project/app"
    depends_on:
      - redis
